const SPELLING_TABLES = {

	"ipa":	{
		"ko kai":	["k",	"k̚"],	
		"kho khai":	["kʰ",	"k̚"],	
		"kho khuat":	["kʰ",	"k̚"],	
		"kho khwai":	["kʰ",	"k̚"],	
		"kho khon":	["kʰ",	"k̚"],	
		"kho ra-khang":	["kʰ",	"k̚"],	
		"ngo ngu":	["ŋ",	"ŋ"],	
		"cho chan":	["tɕ",	"t̚"],	
		"cho ching":	["tɕʰ",	""],	
		"cho chang":	["tɕʰ",	"t̚"],	
		"so so":	["s",	"t̚"],	
		"cho choe":	["tɕʰ",	""],	
		"yo ying":	["j",	"n"],	
		"do cha-da":	["d",	"t̚"],	
		"to pa-tak":	["t",	"t̚"],	
		"tho than":	["tʰ",	"t̚"],	
		"tho montho":	["tʰ",	"t̚"],	
		"tho phu-thao":	["tʰ",	"t̚"],	
		"no nen":	["n",	"n"],	
		"do dek":	["d",	"t̚"],	
		"to tao":	["t",	"t̚"],	
		"tho thung":	["tʰ",	"t̚"],	
		"tho thahan":	["tʰ",	"t̚"],	
		"tho thong":	["tʰ",	"t̚"],	
		"no nu":	["n",	"n"],	
		"bo baimai":	["b",	"p̚"],	
		"po pla":	["p",	"p̚"],	
		"pho phueng":	["pʰ",	""],	
		"fo fa":			["f",	""],	
		"pho phan":			["pʰ",	"p̚"],	
		"fo fan":			["f",	"p̚"],	
		"pho sam-phao":		["pʰ",	"p̚"],	
		"mo ma":			["m",	"m"],	
		"yo yak":			["y",	""],	
		"ro ruea":			["r",	"n"],	
		"ru":				["",	""],	
		"lo ling":			["l",	"n"],	
		"lu":				["",	""],	
		"wo waen":			["w",	""],	
		"so sala":			["s",	"t̚"],	
		"so rue-si":		["s",	"t̚"],	
		"so suea":			["s",	"t̚"],	
		"ho hip":			["h",	""],	
		"lo chu-la":		["l",	"n"],	
		"o ang":			["",	""],	
		"ho nok-huk":		["h",	""],	


		"sara a":			["a",	"aː"],	
		"sara i":			["i",	"iː"],	
		"sara ue":			["ɯ",	"ɯː"],	
		"sara u":			["u",	"uː"],	
		"sara e":			["e",	"eː"],	
		"sara ae":			["ɛ",	"ɛː"],	
		"sara o":			["o",	"oː"],	
		"sara ow":			["ɔ",	"ɔː"],	
		"sara oe":			["ɤʔ",	"ɤː"],	
		"sara ia":			["iaʔ",	"ia"],	
		"sara uea":			["ɯaʔ",	"ɯa"],	
		"sara ua":			["uaʔ",	"ua"],	
		"sara i + wo waen":	["iu",	"iːu"],	
		"sara e + wo waen":	["eu",	"eːu"],	
		"sara ae + wo waen":	["ɛu",	"ɛːu"],	
		"sara ao":	["au",	"aːu"],	
		"sara a + wo waen":	["au",	"aːu"],	
		"sara ia + wo waen":	["iauʔ",	"iau"],	
		"sara a + yo yak":	["ai",	"aːi"],	
		"sara ai":	["ai",	"aːi"],	
		"sara o + yo yak":	["ɔi",	"ɔːi"],	
		"sara u + yo yak":	["ui",	"uːi"],	
		"sara oe + yo yak":	["ɤi",	"ɤːi"],	
		"sara ua + yo yak":	["uaiʔ",	"uai"],	
		"sara uea + yo yak":	["ɯaiʔ",	"ɯai"],	
		"sara am":	["am",	"aːm"],	
		"rue":	["rɯ",	"rɯː"],	
		"lue":	["lɯ",	"lɯː"],
		"TONE_MARKER_STYLE":	'none',
		"INHERENT_VOWEL":	'a' // 'ā';
	},	

	"rtgs":	{
		"ko kai":	["k",	"k"],	
		"kho khai":	["kh",	"k"],	
		"kho khuat":	["kh",	"k"],	
		"kho khwai":	["kh",	"k"],	
		"kho khon":	["kh",	"k"],	
		"kho ra-khang":	["kh",	"k"],	
		"ngo ngu":	["ng",	"ng"],	
		"cho chan":	["ch",	"t"],	
		"cho ching":	["ch",	""],	
		"cho chang":	["ch",	"t"],	
		"so so":	["s",	"t"],	
		"cho choe":	["ch",	""],	
		"yo ying":	["y",	"n"],	
		"do cha-da":	["d",	"t"],	
		"to pa-tak":	["t",	"t"],	
		"tho than":	["th",	"t"],	
		"tho montho":	["th",	"t"],	
		"tho phu-thao":	["th",	"t"],	
		"no nen":	["n",	"n"],	
		"do dek":	["d",	"t"],	
		"to tao":	["t",	"t"],	
		"tho thung":	["th",	"t"],	
		"tho thahan":	["th",	"t"],	
		"tho thong":	["th",	"t"],	
		"no nu":	["n",	"n"],	
		"bo baimai":	["b",	"p"],	
		"po pla":	["p",	"p"],	
		"pho phueng":	["ph",	""],	
		"fo fa":	["f",	"f"],	
		"pho phan":	["ph",	"p"],	
		"fo fan":	["f",	"p"],	
		"pho sam-phao":	["ph",	"p"],	
		"mo ma":	["m",	"m"],	
		"yo yak":	["y",	""],	
		"ro ruea":	["r",	"n"],	
		"ru":	["",	""],	
		"lo ling":	["l",	"n"],	
		"lu":	["",	""],	
		"wo waen":	["w",	""],	
		"so sala":	["s",	"t"],	
		"so rue-si":	["s",	"t"],	
		"so suea":	["s",	"t"],	
		"ho hip":	["h",	""],	
		"lo chu-la":	["l",	"n"],	
		"o ang":	["",	""],	
		"ho nok-huk":	["h",	""],	


		"sara a":	["a",	"a"],	
		"sara i":	["i",	"i"],	
		"sara ue":	["ue",	"ue"],	
		"sara u":	["u",	"u"],	
		"sara e":	["e",	"e"],	
		"sara ae":	["ae",	"ae"],	
		"sara o":	["o",	"o"],	
		"sara ow":	["o",	"o"],	
		"sara oe":	["oe",	"oe"],	
		"sara ia":	["ia",	"ia"],	
		"sara uea":	["uea",	"uea"],	
		"sara ua":	["ua",	"ua"],	
		"sara i + wo waen":	["io",	"io"],	
		"sara e + wo waen":	["eo",	"eo"],	
		"sara ae + wo waen":	["aeo",	"aeo"],	
		"sara ao":	["ao",	"ao"],	
		"sara a + wo waen":	["ao",	"ao"],	
		"sara ia + wo waen":	["iao",	"iao"],	
		"sara a + yo yak":	["ai",	"ai"],	
		"sara ai":	["ai",	"ai"],	
		"sara o + yo yak":	["oi",	"oi"],	
		"sara u + yo yak":	["ui",	"ui"],	
		"sara oe + yo yak":	["oei",	"oei"],	
		"sara ua + yo yak":	["uai",	"uai"],	
		"sara uea + yo yak":	["ueai",	"ueai"],	
		"sara am":	["am",	"am"],	
		"rue":	["rue",	"rue"],	
		"lue":	["lue",	"lue"],	
		"TONE_MARKER_STYLE":	'none',	
		"INHERENT_VOWEL":	'a'// 'ā';

	},	

	"thaiphon":	{
		"ko kai":	["k",	"k"],	
		"kho khai":	["kh",	"k"],	
		"kho khuat":	["kh",	"k"],	
		"kho khwai":	["kh",	"k"],	
		"kho khon":	["kh",	"k"],	
		"kho ra-khang":	["kh",	"k"],	
		"ngo ngu":	["ng",	"ng"],	
		"cho chan":	["j",	"t"],	
		"cho ching":	["ch",	"t"],	
		"cho chang":	["ch",	"t"],	
		"so so":	["s",	"s"],	
		"cho choe":	["ch",	"t"],	
		"yo ying":	["y",	"n"],	
		"do cha-da":	["d",	"d"],	
		"to pa-tak":	["t",	"t"],	
		"tho than":	["th",	"t"],	
		"tho montho":	["th",	"t"],	
		"tho phu-thao":	["th",	"t"],	
		"no nen":	["n",	"n"],	
		"do dek":	["d",	"t"],	
		"to tao":	["t",	"t"],	
		"tho thung":	["th",	"t"],	
		"tho thahan":	["th",	"t"],	
		"tho thong":	["th",	"t"],	
		"no nu":	["n",	"n"],	
		"bo baimai":	["b",	"p"],	
		"po pla":	["p",	"p"],	
		"pho phueng":	["ph",	"p"],	
		"fo fa":	["f",	"f"],	
		"pho phan":	["ph",	"p"],	
		"fo fan":	["f",	"f"],	
		"pho sam-phao":	["ph",	"p"],	
		"mo ma":	["m",	"m"],	
		"yo yak":	["y",	""],	
		"ro ruea":	["r",	"n"],	
		"ru":	["",	""],	
		"lo ling":	["l",	"l"],	
		"lu":	["",	""],	
		"wo waen":	["w",	""],	
		"so sala":	["s",	"t"],	
		"so rue-si":	["s",	"t"],	
		"so suea":	["s",	"s"],	
		"ho hip":	["h",	"h"],	
		"lo chu-la":	["l",	"l"],	
		"o ang":	["",	""],	
		"ho nok-huk":	["h",	"h"],	


		"sara a":	["a",	"ā"],	
		"sara i":	["i",	"ī"],	
		"sara ue":	["eu",	"eū"],	
		"sara u":	["u",	"ū"],	
		"sara e":	["e",	"ē"],	
		"sara ae":	["ae",	"aē"],	
		"sara o":	["o",	"ō"],	
		"sara ow":	["ǿ",	"ø"],	
		"sara oe":	["oe",	"oē"],	
		"sara ia":	["ie",	"īe"],	
		"sara uea":	["uea",	"eūa"],	
		"sara ua":	["ua",	"ūa"],	
		"sara i + wo waen":	["iu",	"iū"],	
		"sara e + wo waen":	["eo",	"ēo"],	
		"sara ae + wo waen":	["aeo",	"aēo"],	
		"sara ao":	["ao",	"āo"],	
		"sara a + wo waen":	["ao",	"āo"],	
		"sara ia + wo waen":	["ao",	"īo"],	
		"sara a + yo yak":	["ai",	"āi"],	
		"sara ai":	["ai",	"āi"],	
		"sara o + yo yak":	["ǿi",	"øi"],	
		"sara u + yo yak":	["ui",	"ūi"],	
		"sara oe + yo yak":	["oei",	"oēi"],	
		"sara ua + yo yak":	["uay",	"ūay"],	
		"sara uea + yo yak":	["euay",	"eūay"],	
		"sara am":	["am",	"ām"],	
		"rue":	["rue",	"rūe"],	
		"lue":	["lue",	"lūe"],	
		"INHERENT_VOWEL":	'a', // 'ā';
		"TONE_MARKER_STYLE":	'thaiphon'
	},	
	"thailang":	{
		"ko kai":		["g",	"k"],	
		"kho khai":		["kh",	"k"],	
		"kho khuat":	["kh",	"k"],	
		"kho khwai":	["kh",	"k"],	
		"kho khon":		["kh",	"k"],	
		"kho ra-khang":	["kh",	"k"],	
		"ngo ngu":		["ng",	"ng"],	
		"cho chan":		["j",	"t"],	
		"cho ching":	["ch",	"t"],	
		"cho chang":	["ch",	"t"],	
		"so so":		["s",	"s"],	
		"cho choe":		["ch",	"t"],	
		"yo ying":		["y",	"n"],	
		"do cha-da":	["d",	"d"],	
		"to pa-tak":	["dt",	"t"],	
		"tho than":		["th",	"t"],	
		"tho montho":	["th",	"t"],	
		"tho phu-thao":	["th",	"t"],	
		"no nen":		["n",	"n"],	
		"do dek":		["d",	"t"],	
		"to tao":		["dt",	"t"],	
		"tho thung":	["th",	"t"],	
		"tho thahan":	["th",	"t"],	
		"tho thong":	["th",	"t"],	
		"no nu":		["n",	"n"],	
		"bo baimai":	["b",	"p"],	
		"po pla":		["bp",	"p"],	
		"pho phueng":	["ph",	"p"],	
		"fo fa":		["f",	"f"],	
		"pho phan":		["ph",	"p"],	
		"fo fan":		["f",	"f"],	
		"pho sam-phao":	["ph",	"p"],	
		"mo ma":		["m",	"m"],	
		"yo yak":		["y",	""],	
		"ro ruea":		["r",	"n"],	
		"ru":			["",	""],	
		"lo ling":		["l",	"n"],	
		"lu":			["",	""],	
		"wo waen":		["w",	""],	
		"so sala":		["s",	"t"],	
		"so rue-si":	["s",	"t"],	
		"so suea":		["s",	"t"],	
		"ho hip":		["h",	"h"],	
		"lo chu-la":	["l",	"l"],	
		"o ang":		["",	""],	
		"ho nok-huk":	["h",	"h"],	


		"sara a":			["a",	"aa"],	
		"sara i":			["i",	"ee"],	
		"sara ue":			["eu",	"euu"],	
		"sara u":			["oo",	"uu"],	
		"sara e":			["e",	"aeh"],	
		"sara ae":			["ae",	"aae"],	
		"sara o":			["o",	"o:	h"],	
		"sara ow":			["aw",	"aaw"],	
		"sara oe":			["er",	"eer"],	
		"sara ia":			["ie",	"īe"],	
		"sara uea":			["uea",	"eūa"],	
		"sara ua":			["ua",	"ūa"],	
		"sara i + wo waen":	["iu",	"iū"],	
		"sara e + wo waen":	["eo",	"ēo"],	
		"sara ae + wo waen":	["aeo",	"aēo"],	
		"sara ao":	["ao",	"āo"],	
		"sara a + wo waen":	["ao",	"āo"],	
		"sara ia + wo waen":	["ao",	"īo"],	
		"sara a + yo yak":	["ai",	"āi"],	
		"sara ai":	["ai",	"āi"],	
		"sara o + yo yak":	["ǿi",	"øi"],	
		"sara u + yo yak":	["ui",	"ūi"],	
		"sara oe + yo yak":	["oei",	"oēi"],	
		"sara ua + yo yak":	["uay",	"ūay"],	
		"sara uea + yo yak":	["euay",	"eūay"],	
		"sara am":	["am",	"ām"],	
		"rue":	["rue",	"rūe"],	
		"lue":	["lue",	"lūe"],	
		"TONE_MARKER_STYLE":	'none',	
		"INHERENT_VOWEL":	'a'// 'ā';
	}


};